project:
  type: website

website:
  title: "Grupo de Estudio para Estadística Correlacional"
  navbar:
    logo: Correlacional/img/logoidea.png
    left:
      - href: presentacion.qmd
        text: Presentación
      - href: sesiones.qmd
        text: Sesiones

format:
  html:
    theme: minty
    css: styles.css
    toc: true