project:
  type: website
  output-dir: ../docs
  resources:
    - input/guia-ejercicios.pdf
    - input/guia-ejercicios.docx

website:
  title: "Grupo de Estudio para Estadística Correlacional"
  navbar:
    logo: img/logoidea.png
    left:
      - href: presentacion.qmd
        text: Presentación
      - href: sesiones.qmd
        text: Sesiones

  sidebar:
    - title: "Sesiones"
      style: "docked"
      search: false
      contents:
        - sesiones.qmd
        - section: "Todas las sesiones"
          contents:
            - sesiones/sesion-1.qmd
            - section: "Sesión 2"
              contents:
                - sesion-2-material.qmd
            - section: "Sesión 3"
              contents:
                - sesiones/sesion-3.qmd
              
            

format:
  html:
    theme: minty
    css: styles.css
    toc: true